<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="country"
           targetNamespace="country" elementFormDefault="qualified">

    <!-- REQUEST TYPES -->

    <xs:element name="AllRequest" type="xs:anyType"/>

    <xs:element name="CountryByIdRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AddRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="tns:CountryInput"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UpdateRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="country" type="tns:CountryInput"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- RESPONSE TYPES -->

    <xs:element name="AllResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="tns:CountryResponse" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CountryByIdResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="countryName" type="xs:string"/>
                <xs:element name="countryCode" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AddResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="countryName" type="xs:string"/>
                <xs:element name="countryCode" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="UpdateResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" type="tns:CountryResponse"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- CUSTOM TYPES -->

    <xs:complexType name="CountryInput">
        <xs:sequence>
            <xs:element name="countryName" type="xs:string"/>
            <xs:element name="countryCode" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CountryResponse">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="countryName" type="xs:string"/>
            <xs:element name="countryCode" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
